name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none' 



environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  fluttertoast: ^8.2.2
  table_calendar: ^3.0.2
  flutter_gemini: ^3.0.0
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  assets:
    - assets/images/fitness_silhouette.png
    - assets/images/red_logo.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/13.png
    - assets/images/14.png
    - assets/images/15.png
    - assets/images/16.png
    - assets/images/22.png
    - assets/images/23.png
    - assets/images/pushup.png
    - assets/images/squat.png
    - assets/images/battleropewaves.png
    - assets/images/benchpress.png
    - assets/images/bicyclecrunches.png
    - assets/images/burpees.png
    - assets/images/diamondpushup.png
    - assets/images/dumbbelldeadlifts.png
    - assets/images/dumbbellinclinepress.png
    - assets/images/flutterkicks.png
    - assets/images/highplanktolowplank.png
    - assets/images/hollowbodycrunch.png
    - assets/images/jumping jacks.png
    - assets/images/jumprope.png
    - assets/images/kettleballswings.png
    - assets/images/legcurl.png
    - assets/images/legextension.png
    - assets/images/legpress.png
    - assets/images/lunges.png
    - assets/images/plank.png
    - assets/images/pullups.png
    - assets/images/reversecrunches.png
    - assets/images/russiantwists.png
    - assets/images/supermans.png
    - assets/images/tricepdips.png
    - assets/images/wallsit.png
  uses-material-design: true

  
